version: '3.4'

services:
  msnet6:
    image: msnet6
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 7126:7126
    depends_on:
      - postgres
  angular:
    image: angular
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 4200:80
  postgres:
    image: postgres:latest
    container_name: vehicle-tracking-db
    ports:
      - 5435:5435
    environment:
      - POSTGRES_PASSWORD=baza1234
      - POSTGRES_DB=Vehicletrackingsystem
      - POSTGRES_USER=postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  

